@startuml escuela
class Estudiante {
    - idEstudiante: int
    - nombre: String
    - edad: int
    + getIdEstudiante(): int
    + getNombre(): String
}

class Curso {
    - idCurso: int
    - nombre: String
    - descripcion: String
    + getIdCurso(): int
    + getNombre(): String
}

class Inscripcion {
    - idInscripcion: int
    - idEstudiante: int
    - idCurso: int
    + getIdInscripcion(): int
}

Estudiante "1" --> "0..*" Inscripcion
Curso "1" --> "0..*" Inscripcion
@enduml
